[workspace]
resolver = "2"
members = [
  "crates/ominiforge",
  "crates/ominiforge-cli",
  "crates/ominiforge-net",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/OminiForge/ominiforge"

[workspace.dependencies]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
