// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session's coarse activity status, as the session list renders it.
 *
 * `Idle` is the resting state (no turn running); the front-end further splits it
 * into "seen" vs "unseen" client-side by comparing [`SessionStatus::latest_seq`]
 * against a locally-remembered acknowledged seq — the gateway cannot know what a
 * user has *looked at*, only what the session is *doing*.
 */
export type ActivityStatus = "running" | "awaiting_input" | "idle";
