// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a human's decision reaches beyond the single call that prompted it
 * (`doc/permission.md` §5). Serialized `snake_case` so a gateway client can
 * send it on the wire alongside the decision.
 */
export type ApprovalScope = "once" | "session" | "profile" | "gateway";
