// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a stored artifact (tool output, intermediate product, ...).
 */
export type ArtifactId = string;
