// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { EventId } from "./EventId";

/**
 * Artifact lifecycle. The event records only a reference; content lives in the
 * artifact store. See `doc/event-schema.md` §8.
 */
export type ArtifactEvent = { "Created": { artifact_id: ArtifactId, 
/**
 * e.g. `"file"`, `"image"`, `"code_block"`.
 */
kind: string, media_type: string, 
/**
 * Artifact-store path or URI.
 */
uri: string, size: bigint, sha256: string | null, source_event_id: EventId | null, } };
