// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fully-assembled content block, persisted as one [`ModelEvent::ContentBlock`].
 *
 * This is the consolidated counterpart to the streaming
 * [`ContentBlockType`] + deltas: instead of one event per token, the collector
 * accumulates a block and records it once, here, with its complete content.
 */
export type BlockContent = { "Text": { text: string, } } | { "Reasoning": { text: string, } } | { "ToolCall": { id: string, name: string, arguments: string, } };
