// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[budget]` (parsed; not yet wired).
 */
export type BudgetSection = { session_max_usd?: number | null, daily_max_usd?: number | null, warn_at_percent?: number | null, };
