// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[budget]`: per-turn round budget and the absolute hard cap.
 *
 * `max_rounds` is the absolute safety net on model rounds in one turn
 * (`doc/todo.md` §7). `round_budget_threshold` + `round_budget_warn_pct`
 * drive the soft round-budget reminder: when the model has spent
 * `warn_pct * threshold` rounds the loop injects a one-shot reminder, and
 * once it has spent the full threshold it injects a reminder every round
 * until the todo list moves or the turn ends.
 */
export type BudgetSection = { session_max_usd?: number | null, daily_max_usd?: number | null, warn_at_percent?: number | null, 
/**
 * Absolute hard cap on model rounds in one turn (`MaxRoundsExceeded`
 * when hit). Default 1000 when unset.
 */
max_rounds?: number | null, 
/**
 * Soft per-step round budget. `0` disables the round-budget reminder
 * entirely. Default 20 when unset.
 */
round_budget_threshold?: number | null, 
/**
 * Fraction of `round_budget_threshold` at which a one-shot warning
 * fires. Default 0.8 when unset.
 */
round_budget_warn_pct?: number | null, };
