// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a case came to exist (`doc/eval.md` §3.1, §8).
 */
export type CaseSource = "manual" | "ingested" | "bootstrap";
