// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file dropped into the scratch workspace before the agent runs.
 */
export type CaseFile = { 
/**
 * Path relative to the scratch workspace root.
 */
path: string, 
/**
 * The file's contents.
 */
content: string, };
