// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a case participates in the regression gate (`doc/eval.md` §4.4).
 */
export type CaseStatus = "approved" | "proposed";
