// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpectedFile } from "./ExpectedFile";

/**
 * How to judge a run — the four buckets of `doc/eval.md` §3.1.
 *
 * `kind` (`snake_case`) selects the variant; each carries only the data its
 * scorer needs. Scorers that consume these are implemented in Step 2.
 */
export type Checker = { "kind": "exact" } | { "kind": "fuzzy" } | { "kind": "tests", 
/**
 * The command to run (e.g. `cargo test`).
 */
command: string, 
/**
 * Substrings that must appear in stdout/stderr for a pass. Empty =
 * exit code alone decides.
 */
pass_patterns?: Array<string>, } | { "kind": "state", 
/**
 * Files whose presence/content is asserted.
 */
expect?: Array<ExpectedFile>, } | { "kind": "judge", 
/**
 * Few-shot critique prompt describing the pass criteria.
 */
rubric: string, };
