// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which layer of the config chain supplied an entry (`doc/lsp.md` §3).
 */
export type ConfigLayer = "builtin" | "global" | "workspace";
