// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of content block a model is streaming.
 *
 * Used on the streaming boundary ([`crate::llm::StreamEvent::BlockStart`]): a
 * `ToolCall` block carries the call `id` and `name` at its start so the agent
 * loop has what it needs to dispatch the tool; the JSON arguments arrive as
 * subsequent deltas. Persisted history uses [`BlockContent`] instead, which
 * carries the fully-assembled block.
 */
export type ContentBlockType = "Text" | "Reasoning" | { "ToolCall": { id: string, name: string, } };
