// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";

/**
 * A unit of tool output. Payloads over 64KB are spilled to the artifact store
 * by the runtime and referenced via [`Content::ArtifactRef`].
 */
export type Content = { "Text": string } | { "Image": { media_type: string, data: Array<number>, } } | { "ArtifactRef": { artifact_id: ArtifactId, media_type: string, } };
