// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[context]`: compaction and injection knobs (parsed; not yet wired).
 */
export type ContextSection = { compaction_threshold?: number | null, 
/**
 * Model reference (`provider/model` or short `model`) used to generate
 * compaction summaries. `None` reuses the session's current model
 * (`doc/context-management.md`).
 */
compaction_model?: string | null, injection_max_tokens?: number | null, };
