// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";
import type { EventPayload } from "./EventPayload";
import type { EventSource } from "./EventSource";
import type { SessionId } from "./SessionId";
import type { TurnId } from "./TurnId";

/**
 * The unified event envelope. Every event carries these fields plus a
 * domain-specific [`EventPayload`]. See `doc/event-schema.md` §2.
 *
 * `session_id` is held in memory but omitted on disk (it is the session
 * directory name); see `doc/session-storage.md` §3.
 */
export type CoreEvent = { 
/**
 * Protocol version, e.g. `"ominiforge.event.v1"`.
 */
schema_version: string, 
/**
 * Monotonic sequence number within the session; guarantees strict order.
 */
seq: bigint, 
/**
 * The session this event belongs to.
 */
session_id: SessionId, 
/**
 * UTC timestamp.
 */
timestamp: string, 
/**
 * Where the event originated.
 */
source: EventSource, 
/**
 * The upstream event that caused this one, if any (causal link).
 */
parent_event_id: EventId | null, 
/**
 * The turn this event belongs to, once a turn has started.
 */
turn_id: TurnId | null, 
/**
 * The domain payload.
 */
payload: EventPayload, };
