// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A live streaming delta, mirroring [`StreamSink`] callbacks.
 */
export type Delta = { "delta": "block_start", index: number, 
/**
 * `text` | `reasoning` | `tool_call`.
 */
kind: string, 
/**
 * Present for a `tool_call` block.
 */
tool: string | null, } | { "delta": "text", index: number, text: string, } | { "delta": "reasoning", index: number, text: string, } | { "delta": "tool_args", index: number, json: string, };
