// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity of an [`ErrorDetail`].
 */
export type ErrorSeverity = "Fatal" | "Error" | "Warning";
