// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorSeverity } from "./ErrorSeverity";
import type { EventId } from "./EventId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Structured error detail, reused across model/tool/error events.
 *
 * Carries more than a string so consumers can route on `code`, `severity`,
 * and `retryable`.
 */
export type ErrorDetail = { code: string, message: string, severity: ErrorSeverity, retryable: boolean, source_event_id: EventId | null, provider_raw: JsonValue | null, };
