// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorDetail } from "./ErrorDetail";

/**
 * A structured error surfaced as its own event. See `doc/event-schema.md` §10.
 */
export type ErrorEvent = { "Raised": ErrorDetail };
