// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseFile } from "./CaseFile";
import type { CaseSource } from "./CaseSource";
import type { CaseStatus } from "./CaseStatus";
import type { Checker } from "./Checker";
import type { Difficulty } from "./Difficulty";
import type { SessionId } from "./SessionId";

/**
 * One eval case: an input to send an agent plus how to judge the result.
 */
export type EvalCase = { 
/**
 * Stable unique id. Also the join key for scores across runs, so it must
 * be unique within a suite and stable across case edits.
 */
id: string, 
/**
 * How this case came to exist. Defaults to [`CaseSource::Manual`].
 */
source: CaseSource, 
/**
 * Whether the case is part of the regression gate. Defaults to
 * [`CaseStatus::Approved`]; auto-ingested cases start `Proposed` and are
 * promoted by human review (`doc/eval.md` §4.4, §8.4).
 */
status: CaseStatus, 
/**
 * For `ingested` cases, the session the case was extracted from — kept for
 * traceability back to the original run. Absent for hand-authored cases.
 */
origin_session?: SessionId | null, 
/**
 * The prompt sent to the agent.
 */
input: string, 
/**
 * Optional string ground truth. Required by the `exact`/`fuzzy` checkers,
 * unused by `tests`/`state`.
 */
target?: string | null, 
/**
 * Free-form labels for dimension slicing in the analysis layer
 * (`doc/eval.md` §6 A4).
 */
tags?: Array<string>, 
/**
 * Optional difficulty hint, also for slicing.
 */
difficulty?: Difficulty | null, 
/**
 * Files seeded into the scratch workspace before the agent runs.
 */
files?: Array<CaseFile>, 
/**
 * How to judge the run.
 */
checker: Checker, };
