// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

/**
 * Where an event came from. `kind` enables fast routing/filtering; `id`
 * names the concrete instance (e.g. `"shell"`, `"mcp://github-server"`).
 */
export type EventSource = { kind: SourceKind, id: string, };
