// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

/**
 * Globally unique event identifier: `session_id` + monotonic `seq`.
 *
 * Within a session only `seq` is needed; cross-session references use the full
 * pair. Persisted events omit `session_id` per line (it is the directory
 * name), so `EventId` here is the in-memory/cross-session form.
 */
export type EventId = { session_id: SessionId, seq: bigint, };
