// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactEvent } from "./ArtifactEvent";
import type { ErrorEvent } from "./ErrorEvent";
import type { HookEvent } from "./HookEvent";
import type { InjectionEvent } from "./InjectionEvent";
import type { ModelEvent } from "./ModelEvent";
import type { SessionEvent } from "./SessionEvent";
import type { ToolEvent } from "./ToolEvent";
import type { TurnEvent } from "./TurnEvent";

/**
 * Domain-tagged payload of a [`super::CoreEvent`].
 */
export type EventPayload = { "Turn": TurnEvent } | { "Model": ModelEvent } | { "Tool": ToolEvent } | { "Session": SessionEvent } | { "Artifact": ArtifactEvent } | { "Injection": InjectionEvent } | { "Hook": HookEvent } | { "Error": ErrorEvent };
