// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An expectation about one workspace file after the run (`state` checker).
 */
export type ExpectedFile = { 
/**
 * Path relative to the scratch workspace root.
 */
path: string, 
/**
 * Exact contents to assert. `None` asserts existence only (or, with
 * `absent = true`, is ignored).
 */
content?: string | null, 
/**
 * Assert the file does *not* exist. Mutually exclusive with `content`.
 */
absent?: boolean, };
