// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatMode } from "./FormatMode";
import type { FormatterView } from "./FormatterView";

/**
 * The full format settings view (`GET /config/format`).
 */
export type FormatConfigView = { 
/**
 * The resolved format mode (highest layer that sets one wins; `file`
 * when none does).
 */
mode: FormatMode, 
/**
 * Every built-in formatter plus user-defined ones, tombstoned built-ins
 * retained (greyed) rather than dropped.
 */
formatters: Array<FormatterView>, };
