// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One configured formatter: a stateless stdin→stdout process call
 * (`doc/format.md` §3).
 *
 * `Serialize` exists for the settings UI's write path (`gateway::langconfig`);
 * every field is written explicitly (the file the user reads back is the
 * full record they sent, with no skipped defaults to second-guess).
 */
export type FormatterConfig = { 
/**
 * Unique name; namespaces the formatter in logs and the UI's
 * "formatted by \<name\>" annotation.
 */
name: string, 
/**
 * The executable to spawn.
 */
command: string, 
/**
 * Arguments passed to `command`. May contain the `{file}` placeholder,
 * replaced with the touched file's name (needed by formatters like
 * `prettier --stdin-filepath <name>` that pick a parser from the name).
 */
args: Array<string>, 
/**
 * Extra environment variables for the subprocess.
 */
env: { [key in string]: string }, 
/**
 * File extensions this formatter handles, without the leading dot
 * (e.g. `"rs"`). A file is routed to the first enabled formatter whose
 * list contains its extension.
 */
extensions: Array<string>, 
/**
 * Whether this formatter is used. A higher-precedence layer sets `false`
 * under a built-in's `name` to disable that default (tombstone
 * semantics, mirroring `doc/lsp.md` §3). Defaults to `true`.
 */
enabled: boolean, 
/**
 * Whether this formatter can format a line range rather than the whole
 * file (`mode = "edit"`). When `false` and `mode = "edit"`, the
 * formatter is skipped with a log — never silently run whole-file
 * (`doc/format.md` §5).
 */
supports_line_range: boolean, 
/**
 * Milliseconds an `edit`/`write` waits for the formatter before giving
 * up and writing the unformatted text (fail-closed, `doc/format.md`
 * §4.3). Bounds the formatting overhead on every file op.
 */
format_timeout_ms: bigint, };
