// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The format mode (`doc/format.md` §5). `file` is the default: most stable,
 * most "project-uniform" — at the cost of touching lines the model didn't.
 */
export type FormatMode = "file" | "edit" | "off";
