// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delta } from "./Delta";
import type { EventId } from "./EventId";
import type { EventPayload } from "./EventPayload";
import type { EventSource } from "./EventSource";
import type { SessionId } from "./SessionId";
import type { TurnId } from "./TurnId";

/**
 * What a front-end sees on the wire for one session. Tagged JSON so a client
 * can switch on `type`.
 */
export type GatewayEvent = { "type": "event", 
/**
 * Protocol version, e.g. `"ominiforge.event.v1"`.
 */
schema_version: string, 
/**
 * Monotonic sequence number within the session; guarantees strict order.
 */
seq: bigint, 
/**
 * The session this event belongs to.
 */
session_id: SessionId, 
/**
 * UTC timestamp.
 */
timestamp: string, 
/**
 * Where the event originated.
 */
source: EventSource, 
/**
 * The upstream event that caused this one, if any (causal link).
 */
parent_event_id: EventId | null, 
/**
 * The turn this event belongs to, once a turn has started.
 */
turn_id: TurnId | null, 
/**
 * The domain payload.
 */
payload: EventPayload, } | { "type": "delta" } & Delta | { "type": "turn_settled", incomplete: string | null, } | { "type": "compacted", new_session_id: string, } | { "type": "notice", message: string, };
