// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a hook decided when it ran.
 *
 * Before hooks can `Pass`/`Modified`/`Blocked`; after hooks only `Observed`.
 * `Failed` covers a hook that errored, timed out, or returned invalid output —
 * the pipeline's response to it is governed by the hook's failure mode
 * (`doc/hook-protocol.md` §9).
 */
export type HookOutcome = "Pass" | "Modified" | { "Blocked": { reason: string, } } | "Observed" | { "Failed": { error: string, } };
