// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookOutcome } from "./HookOutcome";

/**
 * Hook execution at a pipeline point.
 *
 * Recorded so replay and monitoring can see every hook that ran, what it
 * decided, and how long it took: the protocol requires all hook executions to
 * be logged (`doc/hook-protocol.md` §1, §11).
 *
 * A hook that *blocks* additionally produces the point-specific failure event
 * (e.g. a `tool:invoke:before` block emits a paired [`ToolEvent::Failed`] with
 * code `blocked_by_hook`, `doc/hook-protocol.md` §8); this event records the
 * hook's own execution regardless of outcome.
 */
export type HookEvent = { "Executed": { 
/**
 * The hook's configured name.
 */
hook_name: string, 
/**
 * The pipeline point it fired at, e.g. `"tool:invoke:before"`.
 */
hook_point: string, outcome: HookOutcome, duration_ms: bigint, } };
