// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[hooks]` (parsed; not yet wired).
 */
export type HooksSection = { before_tool?: Array<string>, after_tool?: Array<string>, };
