// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectionSource } from "./InjectionSource";

/**
 * Dynamic context injection, recorded so replay can reconstruct exactly what
 * the model saw each turn. See `doc/event-schema.md` §9 and
 * `doc/context-management.md` §5.
 */
export type InjectionEvent = { "ContextInjected": { source: InjectionSource, content: string, token_count: number, } };
