// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What produced an injection. Ordering is kept stable (Memory → Rag → Acp →
 * Hook → Runtime) to avoid needless prefix-cache churn.
 */
export type InjectionSource = "Memory" | "RAG" | "ACP" | "Hook" | "Runtime";
