// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One configured language server. Stdio only, spawned on the host (mirrors
 * [`crate::mcp::McpServerConfig`] — the same trust model applies).
 *
 * `Serialize` exists for the settings UI's write path (`gateway::langconfig`);
 * every field is written explicitly (the file the user reads back is the
 * full record they sent, with no skipped defaults to second-guess).
 */
export type LspServerConfig = { 
/**
 * Unique name; namespaces the server in logs.
 */
name: string, 
/**
 * The executable to spawn.
 */
command: string, 
/**
 * Arguments passed to `command`.
 */
args: Array<string>, 
/**
 * Extra environment variables for the subprocess.
 */
env: { [key in string]: string }, 
/**
 * File extensions this server handles, without the leading dot (e.g.
 * `"rs"`). A file is routed to every enabled server whose list contains
 * its extension (a language may have several: `pyright` + `ruff`).
 */
extensions: Array<string>, 
/**
 * Whether this server is used. A higher-precedence layer sets `false`
 * under a built-in's `name` to disable that default (tombstone semantics,
 * `doc/lsp.md` §3). Defaults to `true`.
 */
enabled: boolean, 
/**
 * Milliseconds a `read`/`edit`/`write` op waits for fresh diagnostics
 * after syncing the doc before giving up and returning without them. Caps
 * the LSP overhead on every file op — see the performance model in
 * `doc/lsp.md` §4.
 */
diag_timeout_ms: bigint, 
/**
 * Milliseconds the *first* touch of this language waits for the
 * `initialize` handshake before proceeding without diagnostics. Full
 * workspace indexing continues in the background regardless of this
 * timeout — it only bounds how long that first op stalls.
 */
init_timeout_ms: bigint, };
