// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigLayer } from "./ConfigLayer";

/**
 * One row of the LSP settings view: the effective server config, the layer
 * that supplied it, and whether its binary is on `PATH`.
 */
export type LspServerView = { 
/**
 * Which layer's `lsp.toml` (or the registry) this row came from.
 */
layer: ConfigLayer, 
/**
 * Whether this row is a registry entry (true even when a higher layer
 * shadowed it — the UI greys registry fields either way).
 */
builtin: boolean, 
/**
 * Best-effort install probe: the command resolves on `PATH`.
 */
installed: boolean, 
/**
 * Unique name; namespaces the server in logs.
 */
name: string, 
/**
 * The executable to spawn.
 */
command: string, 
/**
 * Arguments passed to `command`.
 */
args: Array<string>, 
/**
 * Extra environment variables for the subprocess.
 */
env: { [key in string]: string }, 
/**
 * File extensions this server handles, without the leading dot (e.g.
 * `"rs"`). A file is routed to every enabled server whose list contains
 * its extension (a language may have several: `pyright` + `ruff`).
 */
extensions: Array<string>, 
/**
 * Whether this server is used. A higher-precedence layer sets `false`
 * under a built-in's `name` to disable that default (tombstone semantics,
 * `doc/lsp.md` §3). Defaults to `true`.
 */
enabled: boolean, 
/**
 * Milliseconds a `read`/`edit`/`write` op waits for fresh diagnostics
 * after syncing the doc before giving up and returning without them. Caps
 * the LSP overhead on every file op — see the performance model in
 * `doc/lsp.md` §4.
 */
diag_timeout_ms: bigint, 
/**
 * Milliseconds the *first* touch of this language waits for the
 * `initialize` handshake before proceeding without diagnostics. Full
 * workspace indexing continues in the background regardless of this
 * timeout — it only bounds how long that first op stalls.
 */
init_timeout_ms: bigint, };
