// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a [`Rule`]'s patterns are compared against the input text.
 *
 * The set is deliberately small — the config UI compiles its per-tool controls
 * (e.g. a directory allow-list) down to these primitives, so every mode must be
 * something a non-expert can reason about. Richer matching (glob / regex) can
 * be added as new variants without breaking existing rules.
 */
export type MatchMode = "substring" | "prefix";
