// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[memory]` (parsed; not yet wired).
 */
export type MemorySection = { scopes?: Array<string>, auto_write?: boolean | null, };
