// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

/**
 * One message in a conversation, in provider-neutral form.
 */
export type Message = { "System": { content: string, } } | { "User": { content: string, } } | { "Assistant": { content?: string | null, tool_calls?: Array<ToolCall>, } } | { "Tool": { tool_call_id: string, content: string, } };
