// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockContent } from "./BlockContent";
import type { ErrorDetail } from "./ErrorDetail";
import type { StopReason } from "./StopReason";
import type { Usage } from "./Usage";

/**
 * Model interaction.
 *
 * Streaming arrives as per-token deltas on the provider boundary
 * (`crate::llm::StreamEvent`); persisted history consolidates each content
 * block into one [`ModelEvent::ContentBlock`] rather than one event per token,
 * so the log stays compact and replayable.
 *
 * A model emitting a tool call is a `ModelEvent`; the tool actually running is
 * a [`ToolEvent`] — the two are kept separate. See `doc/event-schema.md` §5.
 */
export type ModelEvent = { "RequestStarted": { request_id: string, provider: string, model: string, temperature: number, max_tokens: number | null, tool_schemas_count: number, input_tokens_estimate: number, } } | { "ContentBlock": { request_id: string, index: number, content: BlockContent, } } | { "RequestCompleted": { request_id: string, stop_reason: StopReason, usage: Usage, duration_ms: bigint, time_to_first_token_ms: bigint | null, provider_request_id: string | null, } } | { "RequestFailed": { request_id: string, duration_ms: bigint, error: ErrorDetail, } };
