// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thinking } from "./Thinking";

/**
 * A model offered by a provider.
 */
export type ModelConfig = { 
/**
 * The model identifier sent to the API (e.g. `gpt-4o`).
 */
id: string, 
/**
 * Maximum context window in tokens.
 */
context_window: number, 
/**
 * Maximum output tokens.
 */
max_output_tokens: number, 
/**
 * Recommended default sampling temperature. Defaults to 0.0.
 */
default_temperature: number, 
/**
 * Whether / how the model reasons before answering. Display-only metadata
 * for the settings UI; it does not change how requests are built.
 */
thinking: Thinking, 
/**
 * The reasoning-effort tiers this model accepts, as raw provider strings
 * (e.g. `["low", "medium", "high"]` or `["high", "max"]`). Kept verbatim
 * because providers name tiers differently; empty = no selectable tiers.
 */
think_efforts?: Array<string>, 
/**
 * Input modalities beyond text the model accepts (e.g. `["image", "video"]`).
 * Empty = text only. Display-only metadata.
 */
modalities?: Array<string>, };
