// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[model]`: which model to use and parameter overrides.
 */
export type ModelSection = { 
/**
 * Default model reference, `provider_name/model_id` or short `model_id`.
 */
default?: string | null, 
/**
 * Fallback model reference (parsed; automatic fallback is a later phase).
 */
fallback?: string | null, 
/**
 * Overrides the model's `default_temperature`.
 */
temperature?: number | null, 
/**
 * Overrides the model's `max_output_tokens`.
 */
max_output_tokens?: number | null, 
/**
 * Default reasoning-effort tier for sessions on this profile, as a raw
 * tier name the chosen model declares (`low`/`high`/`max`). Resolved
 * against the model's `think_efforts`; per-turn picks override it.
 */
think_effort?: string | null, };
