// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thinking } from "./Thinking";

/**
 * One selectable model offered by a provider, for a per-session override.
 *
 * The override is sent back as `provider/model_id` (the qualified identity),
 * since two providers may serve the same `model_id`.
 */
export type ModelSummary = { 
/**
 * Provider name (e.g. `openai-main`).
 */
provider: string, 
/**
 * Model id sent to the API (e.g. `gpt-4o`).
 */
model_id: string, 
/**
 * Maximum context window in tokens (shown alongside the model).
 */
context_window: number, 
/**
 * Whether / how the model reasons (drives the effort picker's visibility).
 */
thinking: Thinking, 
/**
 * Selectable reasoning-effort tiers (raw provider strings; empty = none).
 */
think_efforts: Array<string>, };
