// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pricing } from "./Pricing";

/**
 * A model offered by a provider.
 */
export type ModelConfig = { 
/**
 * The model identifier sent to the API (e.g. `gpt-4o`).
 */
id: string, 
/**
 * Maximum context window in tokens.
 */
context_window: number, 
/**
 * Maximum output tokens.
 */
max_output_tokens: number, 
/**
 * Recommended default sampling temperature. Defaults to 0.0.
 */
default_temperature: number, 
/**
 * Cost metadata for the monitor's estimation (optional).
 */
pricing?: Pricing | null, };
