// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a workspace's `[[mounts]]`: bind a named anchor's host directory
 * into the guest (`doc/sandbox.md` §3.7). The anchor names a *sharing scope*
 * (session-private / workspace-shared / gateway-global) rather than a fixed
 * purpose — the user composes what to put there.
 */
export type MountSpec = { 
/**
 * Sharing scope: `session` (per-session private), `workspace` (shared across
 * sessions in this workspace), or `gateway` (global). Resolved to a host
 * root in the registry, which owns the ids and gateway root.
 */
anchor: string, 
/**
 * Relative subpath under the anchor root. Absent = the anchor root itself.
 * A `..` escape is rejected at resolution (fail-loud).
 */
path?: string | null, 
/**
 * Absolute mount point inside the guest.
 */
guest: string, 
/**
 * Mount read-only. Defaults to `false` (read-write).
 */
ro: boolean, };
