// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[network]`: the sandbox network egress policy for sessions on this profile.
 *
 * (`doc/sandbox.md` §6.2). Wired: `assemble` derives the sandbox's
 * [`NetworkPolicy`](crate::sandbox::NetworkPolicy) from this section, falling
 * back to the gateway default when `policy` is unset (`doc/profile.md` §7).
 */
export type NetworkSection = { 
/**
 * Egress policy: `isolated` (no network), `allowlist` (only `allow` hosts),
 * or `open` (unrestricted). `None` inherits the gateway default.
 */
policy?: string | null, 
/**
 * Hosts reachable under the `allowlist` policy; ignored otherwise.
 */
allow?: Array<string>, };
