// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The four ways a session can come into being. See `doc/session-storage.md` §5.
 */
export type OriginKind = "new" | "fork" | "compaction" | "reconfiguration";
