// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OriginKind } from "./OriginKind";
import type { SessionId } from "./SessionId";

/**
 * How a session was born. `kind` carries the semantics; `parent_id` and
 * `fork_at_seq` are shared across the non-`new` kinds.
 */
export type Origin = { kind: OriginKind, 
/**
 * The session this one derives from. Absent only for `new`.
 */
parent_id?: SessionId | null, 
/**
 * The parent seq this session forked at. Present only for `fork`.
 */
fork_at_seq?: bigint | null, };
