// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalScope } from "./ApprovalScope";
import type { PermissionOutcome } from "./PermissionOutcome";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A permission-gate decision on a tool call (`doc/permission.md` §6).
 *
 * The gate classifies each call before it runs; an `ask` suspends it for a
 * human. Both the request and its resolution are recorded so the log is a
 * complete audit trail *and* a front-end can reconstruct a pending prompt after
 * a reload (the live `GatewayEvent::ApprovalRequested` is only an instant
 * hint). A denied call additionally surfaces to the model as a
 * [`ToolEvent::Failed`] (`denied_by_policy` / `denied_by_user`); this event is
 * the parallel audit record, not the model-facing result.
 */
export type PermissionEvent = { "Requested": { 
/**
 * The model-assigned tool-call id, correlating this to the `Decided`
 * event and the underlying `ToolEvent`.
 */
call_id: string, tool_name: string, input: JsonValue, } } | { "Decided": { call_id: string, outcome: PermissionOutcome, decided_by: string, 
/**
 * How far a human's decision reaches (`once` / `session` / `profile` /
 * `gateway`); `None` when no human decided (a policy deny or a
 * fail-closed auto-denial). Optional so older logs still deserialize.
 */
scope?: ApprovalScope | null, } };
