// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a [`PermissionEvent::Requested`] resolved.
 */
export type PermissionOutcome = "Approved" | "Rejected" | "AutoDenied";
