// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rule } from "./Rule";

/**
 * A tool-call gate: three ordered rule lists whose precedence is fixed by
 * [`evaluate`](Self::evaluate).
 *
 * The empty policy allows everything, so a profile with no `[permission]`
 * section imposes no gate — existing behavior is preserved
 * (`doc/permission.md` §2).
 */
export type PermissionPolicy = { 
/**
 * Rules that, when matched, block the call. Highest precedence.
 */
deny?: Array<Rule>, 
/**
 * Rules that, when matched (and no deny rule matched), run the call
 * without asking — pinned approvals (`doc/permission.md` §5). Outranks
 * `ask`.
 */
allow?: Array<Rule>, 
/**
 * Rules that, when matched (and neither deny nor allow matched), require
 * human approval.
 */
ask?: Array<Rule>, };
