// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-million-token pricing, used by the monitor to estimate cost. Stored in
 * config (not in the event stream) so history can be recomputed with current
 * prices. See `doc/monitor.md` §6.
 */
export type Pricing = { input_per_million: number, output_per_million: number, cache_read_per_million?: number | null, cache_write_per_million?: number | null, };
