// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetSection } from "./BudgetSection";
import type { ContextSection } from "./ContextSection";
import type { HooksSection } from "./HooksSection";
import type { MemorySection } from "./MemorySection";
import type { ModelSection } from "./ModelSection";
import type { NetworkSection } from "./NetworkSection";
import type { ProfileMeta } from "./ProfileMeta";
import type { PromptSection } from "./PromptSection";
import type { SkillsSection } from "./SkillsSection";
import type { ToolsSection } from "./ToolsSection";

/**
 * A parsed profile. Optional sections default so partial files load; unknown
 * keys are ignored for forward compatibility.
 */
export type Profile = { profile: ProfileMeta, prompt: PromptSection, model: ModelSection, tools: ToolsSection, context: ContextSection, skills: SkillsSection, memory: MemorySection, budget: BudgetSection, hooks: HooksSection, network: NetworkSection, };
