// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[profile]`: identity and inheritance.
 */
export type ProfileMeta = { name: string, description?: string | null, 
/**
 * Single-inheritance parent profile name (§4).
 */
extends?: string | null, };
