// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A profile's listable identity: its name and human-readable description.
 *
 * Surfaced to a front-end choosing a profile for a new session (`doc/profile.md`
 * §3.1). Deliberately shallow — enumerating profiles must not resolve the
 * `extends` chain (a broken parent must not hide a usable child).
 */
export type ProfileSummary = { 
/**
 * Profile name (the `<name>.toml` the session binds to).
 */
name: string, 
/**
 * Human-readable description from `[profile].description`, if set.
 */
description: string | null, };
