// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[prompt]`: the system prompt, inline or from a file.
 */
export type PromptSection = { system?: string | null, 
/**
 * Path (relative to the profile file) to read the system prompt from.
 */
system_file?: string | null, };
