// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelConfig } from "./ModelConfig";
import type { ProviderType } from "./ProviderType";

/**
 * One configured provider and the models it serves.
 */
export type ProviderConfig = { 
/**
 * Unique identifier; profiles reference it in `provider_name/model_id`.
 */
name: string, 
/**
 * Wire protocol. See [`ProviderType`].
 */
type: ProviderType, 
/**
 * API endpoint root (e.g. `https://api.openai.com/v1`).
 */
base_url: string, 
/**
 * The name of the environment variable holding this provider's API key.
 * The key itself is never stored in config.
 */
api_key_env: string, 
/**
 * Models this provider serves.
 */
models: Array<ModelConfig>, };
