// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire protocol a provider speaks.
 *
 * Only `openai-chat` has a wired adapter in Phase 1; the others parse so full
 * config files load, but selecting them surfaces
 * [`ConfigError::UnsupportedProviderType`](super::ConfigError).
 */
export type ProviderType = "openai-chat" | "openai-completion" | "anthropic" | "custom";
