// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchMode } from "./MatchMode";

/**
 * One rule in a [`PermissionPolicy`]: it matches a tool call when the call's
 * tool name matches [`tool`](Self::tool) **and** the input satisfies the
 * rule's field / mode / pattern test.
 *
 * A rule carries no verdict of its own — which list (`deny`, `allow`, or
 * `ask`) it sits in is the verdict (`doc/permission.md` §3). This keeps the
 * table readable:
 * every rule under `deny` denies, every rule under `allow` runs, every rule
 * under `ask` asks.
 *
 * The structured shape (`field` + `mode` + `negate`) is what the config UI's
 * per-tool cards compile to; a hand-written TOML rule that sets only `contains`
 * still works (see the field docs).
 *
 * [`Default`] yields an empty rule with `tool = ""`, which matches no real tool
 * — a harmless base for `..Default::default()` in construction.
 */
export type Rule = { 
/**
 * The tool name this rule applies to. `"*"` matches any tool; otherwise the
 * match is exact. A rule scoped to `"*"` with no patterns matches every call
 * (a catch-all).
 */
tool: string, 
/**
 * Which input field the patterns test. `None` searches **every** string
 * value in the input recursively (the legacy behavior — a pattern matches
 * wherever it lands). `Some("command")` restricts the test to that
 * top-level field, so a `shell.command` rule never accidentally fires on
 * some other string. A named field that is absent/non-string yields no text
 * (the rule then matches only if [`negate`](Self::negate) is set).
 */
field?: string | null, 
/**
 * How [`patterns`](Self::patterns) are compared (substring / prefix).
 */
mode?: MatchMode, 
/**
 * The patterns to test. Aliased to `contains` on disk for backward
 * compatibility: an existing `contains = [...]` rule deserializes straight
 * into this field, and it serializes back as `contains` so old files keep
 * their shape.
 *
 * An empty list means "match any input for this tool" (a tool-level rule,
 * e.g. deny the `shell` tool outright) — subject to `negate`.
 */
contains?: Array<string>, 
/**
 * Invert the pattern test. `false` (default) = match when a pattern hits;
 * `true` = match when **no** pattern hits. This is how an allow-list is
 * expressed: "ask `write` when `path` does **not** start with any of
 * `src/`, `tmp/`" is `negate = true`, `mode = prefix`, `field = "path"`. A
 * `negate` rule with an empty pattern list never matches (nothing to fail),
 * so an empty allow-list does not lock the tool out by accident.
 */
negate?: boolean, };
