// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The config-layer model identity for a session: the provider and model.
 *
 * This is what the gateway resolves for the session (`doc/frontend.md`,
 * RUNTIME panel) — the *configured* selection, stable for the session's
 * lifetime — not whatever a given model request happened to use
 * (subagents/forks may differ; that divergence is a runtime-validation
 * concern, not this display source).
 */
export type RuntimeInfo = { 
/**
 * Provider name (e.g. `openai-main`).
 */
provider: string, 
/**
 * Model id sent to the API (e.g. `gpt-4o`).
 */
model: string, 
/**
 * Environment labels detected from the activated session environment (e.g.
 * `["dev shell: impure (nix-shell-env)"]` or `["venv: .venv"]`). Empty
 * when no activation signal is present — the RUNTIME panel only shows the
 * row when non-empty ("detected, therefore shown"; `doc/frontend.md`, B2).
 */
env: Array<string>, };
