// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session's bound sandbox, persisted so its environment survives a process
 * restart (`doc/sandbox.md` §3.2, §3.5).
 *
 * The `backend` names which [`crate::sandbox::SandboxBackend`] produced it;
 * `id` is the backend's persistent handle (a boxlite box id), absent for
 * backends that carry no durable identity (passthrough shares the host
 * workspace and is rebuilt from scratch on re-attach).
 */
export type SandboxDescriptor = { 
/**
 * Backend name, e.g. `"passthrough"` or `"boxlite"`.
 */
backend: string, 
/**
 * Backend-specific persistent id, if the backend has one.
 */
id?: string | null, };
