// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One server's runtime state, surfaced to the UI (`RuntimeInfo.lsp`,
 * `doc/lsp.md` §5.1).
 */
export type ServerState = "starting" | "running" | "failed";
