// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerState } from "./ServerState";

/**
 * A snapshot of one server for display.
 */
export type ServerStatus = { 
/**
 * Config `name`.
 */
name: string, 
/**
 * Extensions it handles.
 */
extensions: Array<string>, 
/**
 * Current state.
 */
state: ServerState, };
