// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated, derived view of one session, produced by folding its events.
 *
 * All counts are saturating.
 */
export type SessionSummary = { total_turns: number, total_model_requests: number, total_tool_calls: number, total_tool_failures: number, total_input_tokens: bigint, total_output_tokens: bigint, total_cache_read_tokens: bigint, 
/**
 * `cache_read / input`, in `[0, 1]`. `0.0` when no input tokens were seen.
 *
 * For a forked/compacted/reconfigured session the inherited context is
 * materialized as `context_snapshot.json` and never re-requested through
 * this session, so it contributes no cache reads — this rate reflects
 * only the session's own requests and reads low right after a branch.
 */
cache_hit_rate: number, 
/**
 * Best current estimate of the context-window occupancy in tokens: the
 * agent ledger's `running()` count persisted on each
 * `RequestStarted::input_tokens_estimate` (the last one wins — that
 * request sent the largest prefix). `0` before the first request. The
 * gateway folds the inherited snapshot's estimate into this for branched
 * sessions, so a fork does not read as an empty context.
 */
context_tokens: number, 
/**
 * The first turn's user input, if any — a human-readable title for the
 * session list (`doc/frontend.md`). `None` for sessions with no user turn
 * (e.g. an empty draft that was never sent). Not truncated server-side; the
 * UI clips it for display.
 */
first_user_input: string | null, 
/**
 * The timestamp of the *last* turn whose user input was non-empty — the
 * session's "last activity" for list ordering (`doc/frontend.md`). Unlike
 * [`first_user_input`](Self::first_user_input) (first-write-wins as a stable
 * title), this is last-write-wins so the list surfaces recently-touched
 * sessions. Deliberately keyed on the *user* message, not any event, so a
 * long-running agent turn does not churn the ordering. `None` for a session
 * with no real user turn (the UI falls back to `created_at`).
 */
last_user_message_at: string | null, 
/**
 * `tool_name → call count` (includes failures).
 */
tools_used: { [key in string]: bigint }, 
/**
 * One entry per error code, with how many times it occurred.
 */
errors: { [key in string]: bigint }, };
