// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";
import type { SandboxDescriptor } from "./SandboxDescriptor";
import type { SessionId } from "./SessionId";

/**
 * The contents of a session's `session.toml`.
 */
export type SessionMeta = { 
/**
 * The session id (also the directory name).
 */
id: SessionId, 
/**
 * The profile this session is bound to, if any.
 */
profile_id?: string | null, 
/**
 * When the session was created.
 */
created_at: string, 
/**
 * The working directory. `None` means filesystem tools are restricted
 * (research / chat / planning sessions).
 */
workspace?: string | null, 
/**
 * The sandbox this session's execution environment is bound to. Records
 * which backend created it and (for backends with persistent identity, e.g.
 * boxlite) the id needed to re-attach the environment after a process
 * restart (`doc/sandbox.md` §3.5). `None` for sessions created before the
 * sandbox subsystem, or with no execution environment.
 */
sandbox?: SandboxDescriptor | null, 
/**
 * How this session came to exist.
 */
origin: Origin, };
