// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated, derived view of one session, produced by folding its events.
 *
 * All counts are saturating; `cost_usd` is `None` when no priced model ran
 * (so the UI can say "unpriced" rather than print a misleading `$0.00`).
 */
export type SessionSummary = { total_turns: number, total_model_requests: number, total_tool_calls: number, total_tool_failures: number, total_input_tokens: bigint, total_output_tokens: bigint, total_cache_read_tokens: bigint, 
/**
 * `cache_read / input`, in `[0, 1]`. `0.0` when no input tokens were seen.
 */
cache_hit_rate: number, 
/**
 * Derived USD cost, or `None` if no model with pricing ran.
 */
cost_usd: number | null, 
/**
 * `tool_name → call count` (includes failures).
 */
tools_used: { [key in string]: bigint }, 
/**
 * One entry per error code, with how many times it occurred.
 */
errors: { [key in string]: bigint }, };
