// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";
import type { SandboxDescriptor } from "./SandboxDescriptor";
import type { SessionId } from "./SessionId";

/**
 * The contents of a session's `session.toml`.
 */
export type SessionMeta = { 
/**
 * The session id (also the directory name).
 */
id: SessionId, 
/**
 * The profile this session is bound to, if any.
 */
profile_id?: string | null, 
/**
 * The per-session model override (`provider/model_id`), if one was chosen
 * at creation instead of the profile default. Stored so the RUNTIME panel
 * resolves the session's real model, and so an idle-evicted session respawns
 * on the same model rather than falling back to the profile default. `None`
 * means the profile default applies. This is session-private; it is never
 * written back to `providers.toml` or the profile.
 */
model?: string | null, 
/**
 * When the session was created.
 */
created_at: string, 
/**
 * The working directory. `None` means filesystem tools are restricted
 * (research / chat / planning sessions).
 */
workspace?: string | null, 
/**
 * The sandbox this session's execution environment is bound to. Records
 * which backend created it and (for backends with persistent identity, e.g.
 * boxlite) the id needed to re-attach the environment after a process
 * restart (`doc/sandbox.md` §3.5). `None` for sessions created before the
 * sandbox subsystem, or with no execution environment.
 */
sandbox?: SandboxDescriptor | null, 
/**
 * How this session came to exist.
 */
origin: Origin, 
/**
 * Whether this session is archived (`doc/session-storage.md` §9): retired
 * from every active listing, files kept readable. The `.archived` sidecar
 * marker — not this field — is the source of truth; `read_meta` stamps it
 * from the marker on every read so API consumers see the real state.
 * Skipped when false so active sessions' `session.toml` stays untouched.
 */
archived?: boolean, };
