// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStatus } from "./ActivityStatus";
import type { SessionId } from "./SessionId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * One session's status on the wire.
 *
 * Which session, in which workspace, its status, and the latest committed event
 * `seq` (the same monotonic sequence the SSE stream uses as its resume cursor).
 * `latest_seq` lets the front-end decide "unseen" without a second request.
 */
export type SessionStatus = { 
/**
 * The session this status is for.
 */
session_id: SessionId, 
/**
 * The workspace the session belongs to (or the `"none"` sentinel), so a
 * list scoped to one workspace can filter, and a future dashboard rollup can
 * group — without the client re-deriving it.
 */
workspace_id: WorkspaceId, 
/**
 * The coarse activity status.
 */
status: ActivityStatus, 
/**
 * The session's latest committed event `seq` at the time of this status.
 */
latest_seq: bigint, };
