// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a session. ULID format in practice (time-sortable + random).
 */
export type SessionId = string;
