// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";
import type { SessionId } from "./SessionId";

/**
 * The contents of a session's `session.toml`.
 */
export type SessionMeta = { 
/**
 * The session id (also the directory name).
 */
id: SessionId, 
/**
 * The profile this session is bound to, if any.
 */
profile_id?: string | null, 
/**
 * When the session was created.
 */
created_at: string, 
/**
 * The working directory. `None` means filesystem tools are restricted
 * (research / chat / planning sessions).
 */
workspace?: string | null, 
/**
 * How this session came to exist.
 */
origin: Origin, };
