// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionEndReason } from "./SessionEndReason";
import type { SessionId } from "./SessionId";

/**
 * Session lifecycle. `Created` is always the first event and snapshots the
 * initial config so replay is self-contained. See `doc/event-schema.md` §7
 * and `doc/session-storage.md` §3.
 */
export type SessionEvent = { "Created": { profile_id: string | null, tools: Array<string>, workspace: string | null, } } | { "Forked": { parent_session_id: SessionId, fork_at_seq: bigint, } } | "Paused" | "Resumed" | { "Ended": { reason: SessionEndReason, } };
