// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[skills]` (parsed; not yet wired).
 */
export type SkillsSection = { enabled?: Array<string>, };
