// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse classification of an event source.
 *
 * No `Plugin` variant: the WASM plugin model was dropped; external extensions
 * are MCP servers, classified as [`SourceKind::External`].
 */
export type SourceKind = "Model" | "Tool" | "Runtime" | "User" | "System" | "External";
