// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the model stopped generating.
 */
export type StopReason = "EndTurn" | "MaxTokens" | "ToolUse" | "StopSequence";
