// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model's reasoning behaviour, shown in the settings UI's model table.
 *
 * This is richer than a boolean because providers distinguish "always thinks"
 * from "can think if asked": Kimi's `kimi-k2.7-code` always reasons (it cannot
 * be disabled) while `kimi-k2.6` reasons only by default/optionally.
 */
export type Thinking = "none" | "optional" | "always";
