// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolField } from "./ToolField";

/**
 * A human-facing description of a tool for the permission-config UI.
 *
 * This is NOT what the model sees (that is [`ToolDescriptor`]) — it is the
 * metadata the front-end turns into a per-tool gating card (`doc/permission.md`
 * §3.2): a friendly label, the one-line purpose, and which input fields a rule
 * may target (so the user picks a field from a dropdown instead of typing a
 * JSON path they cannot know).
 *
 * Serialized to the front-end via `GET /tools`; only built-in tools have a
 * hand-authored catalog entry today. A tool with no entry (e.g. an MCP tool)
 * still gates fine — the UI falls back to a generic "whole input" card.
 */
export type ToolInfo = { 
/**
 * The tool name a [`crate::permission::Rule`] targets (its `tool` field).
 */
name: string, 
/**
 * A short human label for the card header (e.g. "运行命令"). Falls back to
 * `name` when absent.
 */
label?: string | null, 
/**
 * One-line purpose, shown under the label.
 */
description?: string | null, 
/**
 * The input fields a rule may scope to. Empty = only whole-input rules make
 * sense for this tool (the UI shows no field dropdown).
 */
fields?: Array<ToolField>, };
