// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a tool came from. The agent loop treats both uniformly; this only
 * drives source-aware monitoring (which MCP server is slow/failing/etc.).
 */
export type ToolSource = "Builtin" | { "Mcp": { server_name: string, } };
