// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One targetable input field of a tool, for the config UI's field dropdown.
 */
export type ToolField = { 
/**
 * The JSON key a rule's `field` targets (e.g. `"command"`, `"path"`).
 */
key: string, 
/**
 * A human label for the field in the dropdown (e.g. "命令", "路径").
 */
label: string, 
/**
 * Whether this field holds a filesystem path — the UI offers prefix
 * (directory allow/deny-list) controls for it, not just substring.
 */
is_path?: boolean, };
