// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool invocation requested by the model. `arguments` is the raw JSON string
 * as produced by the model (parsed by the tool dispatcher, not here).
 */
export type ToolCall = { id: string, name: string, arguments: string, };
