// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Content } from "./Content";

/**
 * The recorded outcome of a tool invocation.
 *
 * A business-level failure is a successful invocation with `is_error = true`;
 * protocol errors surface as a [`ToolEvent::Failed`] instead. The tool layer's
 * `ToolResult` alias is `Result<ToolOutput, ToolError>`. See
 * `doc/tool-protocol.md` §7.
 */
export type ToolOutput = { content: Array<Content>, is_error: boolean, error_code: string | null, };
