// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { ErrorDetail } from "./ErrorDetail";
import type { EventId } from "./EventId";
import type { ToolOutput } from "./ToolOutput";
import type { ToolSource } from "./ToolSource";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Tool execution. `Started` points back at the model tool-call event that
 * triggered it; `Completed`/`Failed` carry timing and output metadata. See
 * `doc/event-schema.md` §6.
 */
export type ToolEvent = { "Started": { tool_call_event_id: EventId, tool_name: string, source: ToolSource, input: JsonValue, working_dir: string | null, } } | { "Completed": { tool_call_event_id: EventId, result: ToolOutput, duration_ms: bigint, output_bytes: number, artifacts_created: Array<ArtifactId>, } } | { "Failed": { tool_call_event_id: EventId, duration_ms: bigint, error: ErrorDetail, } };
