// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[tools]`: which built-in tools and MCP servers are available.
 */
export type ToolsSection = { 
/**
 * Built-in tools to enable. `None` means "all registered built-ins".
 */
builtin?: Array<string> | null, 
/**
 * MCP server names to attach (parsed; MCP client is Phase 2).
 */
mcp_servers?: Array<string>, 
/**
 * Tools to disable even if otherwise enabled.
 */
disabled?: Array<string>, };
