// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";
import type { TurnFailureReason } from "./TurnFailureReason";
import type { TurnId } from "./TurnId";

/**
 * Turn lifecycle.
 *
 * A turn is one iteration of the agent loop and has an explicit state machine:
 * `pending → running → completed | failed | interrupted`. A failed or
 * interrupted turn records its break point so it can resume without the user
 * re-entering input. See `doc/event-schema.md` §4.
 */
export type TurnEvent = { "Started": { turn_id: TurnId, 
/**
 * The user input that opened the turn, when one did. `None` for turns
 * started by a non-user trigger (scheduler, autonomous continuation).
 * Replay reconstructs the opening user message from this field.
 */
input?: string | null, } } | { "Completed": { turn_id: TurnId, } } | { "Failed": { turn_id: TurnId, failed_at_event_id: EventId, retryable: boolean, 
/**
 * Why the turn did not finish cleanly. Optional for backward
 * compatibility with logs written before the field existed; new
 * failures always set it so replay/monitoring can explain the stop
 * without guessing.
 */
reason?: TurnFailureReason | null, } } | { "Interrupted": { turn_id: TurnId, interrupted_at_event_id: EventId, } } | { "Resumed": { turn_id: TurnId, resume_from_event_id: EventId, } };
