// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a turn ended without a clean `Completed`.
 *
 * These are *graceful* stops the loop records and hands back to the caller
 * (the turn's side effects still stand) — not transport/persistence errors.
 * A hard error surfaces as a `Result::Err` (never a [`TurnFailureReason`]) but
 * still leaves a trace: the loop records a `TurnEvent::Failed` with
 * `reason: None` paired with an [`ErrorEvent::Raised`] carrying the detail, so
 * `reason.is_some()` distinguishes a graceful stop from a hard abort. See
 * `doc/event-schema.md` §4 and `doc/plan.md` §6–§7.
 */
export type TurnFailureReason = { "MaxRoundsExceeded": { max_rounds: number, } } | { "PlanStalled": { incomplete_steps: number, } } | { "BlockedByHook": { by: string, reason: string, } };
