// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token accounting reported by the provider.
 *
 * Cost is *not* stored: the monitor derives it from `usage` plus a
 * configurable pricing table, so history can be recomputed with current
 * prices. See `doc/monitor.md` §3, §6.
 */
export type Usage = { input_tokens: number, output_tokens: number, cache_read_tokens: number, cache_write_tokens: number, };
