// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[tools.web_fetch]`: hard network constraints for `web_fetch`, enforced by
 * the tool itself — unlike `[permission]` rules, these never ask a human.
 *
 * The link-local block (cloud metadata, `169.254.0.0/16` / `fe80::/10`) is
 * NOT configurable: it is applied on top of whatever this section says.
 */
export type WebFetchSection = { 
/**
 * Accept plain `http://` URLs (default true; `https://` always works).
 */
allow_http: boolean, 
/**
 * Non-default ports a URL may target; empty = 80/443 only.
 */
allowed_ports?: Array<number>, 
/**
 * CIDRs whose addresses are refused. When set, REPLACES the default
 * private/loopback list (e.g. to unblock Tailscale's CGNAT range) — the
 * hardcoded link-local floor always applies on top.
 */
blocked_cidrs?: Array<string> | null, 
/**
 * When non-empty, only matching hosts are fetched (`*.example.com`
 * matches the apex and every subdomain; `*` matches all).
 */
allowed_domains?: Array<string>, 
/**
 * Matching hosts are always refused, even if `allowed_domains` hits.
 */
blocked_domains?: Array<string>, };
