// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workspace identifier: either a hash of the absolute path, or the sentinel
 * `"none"` for sessions without a workspace.
 */
export type WorkspaceId = string;
