// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountSpec } from "./MountSpec";
import type { NetworkSection } from "./NetworkSection";
import type { PermissionPolicy } from "./PermissionPolicy";

/**
 * The on-disk shape of `<gateway>/.omini/workspaces/<id>.toml`.
 *
 * `[network]`, `[[mounts]]`, and `[permission]` are defined today; the record
 * stays open for further sections (e.g. workspace memory,
 * `doc/workspace-config.md`) without a schema change forcing every file to be
 * rewritten. Unknown keys are ignored for forward compatibility.
 */
export type WorkspaceConfig = { 
/**
 * Sandbox network egress override for sessions in this workspace. `None`
 * (section absent) falls through to the profile / gateway default.
 */
network?: NetworkSection | null, 
/**
 * Auxiliary sandbox mounts (`doc/sandbox.md` §3.7): each binds a named
 * anchor's host directory into the guest. Empty (section absent) = only the
 * workspace mount (§3.3).
 */
mounts?: Array<MountSpec>, 
/**
 * Per-workspace tool-call gate (`doc/permission.md` §3), the **top** tier of
 * the three-tier resolution (`workspace > profile > gateway`). Layered over
 * the profile+gateway policy: its `deny` rules union in (a workspace can add
 * denials, never drop an inherited one — safe because this file is
 * gateway-trusted, not agent-writable), its `ask` list replaces when set.
 * Empty (section absent) contributes nothing.
 *
 * Safe to live here *because* the file is gateway-side and deployer-owned
 * (see the module header): reading a permission grant from the
 * agent-writable project dir would let an agent widen its own gate.
 */
permission?: PermissionPolicy, };
