// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceId } from "./WorkspaceId";

/**
 * One workspace in the dashboard: its path (or `None` for the `"none"` group),
 * the session IDs belonging to it, and the most recent session timestamp.
 */
export type WorkspaceSummary = { 
/**
 * Workspace identifier (hash of path, or `"none"`).
 */
id: WorkspaceId, 
/**
 * Absolute path, or `None` for the no-workspace group.
 */
path: string | null, 
/**
 * Number of sessions in this workspace.
 */
session_count: number, 
/**
 * Most recent session creation time (ISO 8601), or `None` if no sessions.
 */
latest_session_time: string | null, };
